In [1]:
import sys

!{sys.executable} -m pip install numpy pandas matplotlib

  Using cached matplotlib-3.10.8-cp314-cp314-win_amd64.whl.metadata (52 kB)
  Using cached contourpy-1.3.3-cp314-cp314-win_amd64.whl.metadata (5.5 kB)
Using cached matplotlib-3.10.8-cp314-cp314-win_amd64.whl (8.3 MB)
Using cached contourpy-1.3.3-cp314-cp314-win_amd64.whl (232 kB)

   ---------------------------------------- 0/2 [contourpy]
   -------------------- ------------------- 1/2 [matplotlib]
   -------------------- ------------------- 1/2 [matplotlib]
   -------------------- ------------------- 1/2 [matplotlib]
   -------------------- ------------------- 1/2 [matplotlib]
   -------------------- ------------------- 1/2 [matplotlib]
   -------------------- ------------------- 1/2 [matplotlib]
   -------------------- ------------------- 1/2 [matplotlib]
   -------------------- ------------------- 1/2 [matplotlib]
   -------------------- ------------------- 1/2 [matplotlib]
   -------------------- ------------------- 1/2 [matplotlib]
   -------------------- ------------------- 1/2 

In [1]:
import numpy as np
arr_1d = np.arange(1, 11)
print(arr_1d)

[ 1  2  3  4  5  6  7  8  9 10]


In [2]:
arr_2d = np.random.randint(0, 10, (3, 3))
print("\nМассив 2D (3x3):")
print(arr_2d)


Массив 2D (3x3):
[[3 6 2]
 [4 9 5]
 [8 5 6]]


In [3]:
print("Сумма всех элементов:", arr_2d.sum())
print("Среднее значение:", arr_2d.mean())
print("Максимальное значение:", arr_2d.max())

Сумма всех элементов: 48
Среднее значение: 5.333333333333333
Максимальное значение: 9


In [4]:
arr_mult = arr_2d * 2
print("\nУмножили на 2:")
print(arr_mult)


Умножили на 2:
[[ 6 12  4]
 [ 8 18 10]
 [16 10 12]]


In [5]:
arr_replaced = arr_2d.copy()
arr_replaced[arr_replaced > 5] = 0

print("\nЗаменили числа > 5 на 0:")
print(arr_replaced)


Заменили числа > 5 на 0:
[[3 0 2]
 [4 0 5]
 [0 5 0]]
